# Generated by Django 3.2.13 on 2022-08-16 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistration',
            name='phone',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
