# Generated by Django 3.2.13 on 2022-08-16 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_userregistration_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=20)),
                ('catogorie', models.CharField(max_length=50)),
                ('subcat', models.CharField(max_length=50, null=True)),
                ('wight', models.BigIntegerField()),
                ('unit', models.CharField(max_length=50)),
                ('qty', models.BigIntegerField()),
                ('amount', models.BigIntegerField()),
            ],
            options={
                'db_table': 'add_product',
            },
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='phone',
            field=models.BigIntegerField(null=True),
        ),
    ]
