# Generated by Django 3.2.13 on 2022-08-17 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_alter_addproduct_pname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproduct',
            name='amount',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='addproduct',
            name='catogorie',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='addproduct',
            name='description',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='addproduct',
            name='qty',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='addproduct',
            name='unit',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='addproduct',
            name='wight',
            field=models.BigIntegerField(null=True),
        ),
    ]
