# Generated by Django 3.2.13 on 2022-08-17 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0005_auto_20220817_0926'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddProduct',
        ),
    ]
