# Generated by Django 3.2.13 on 2022-08-17 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0006_delete_addproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=100, null=True)),
                ('desc', models.CharField(max_length=200, null=True)),
                ('cat', models.CharField(max_length=100, null=True)),
                ('sub_cat', models.CharField(max_length=100, null=True)),
                ('weight', models.BigIntegerField(null=True)),
                ('unit', models.CharField(max_length=100, null=True)),
                ('qty', models.BigIntegerField(null=True)),
                ('amount', models.BigIntegerField(null=True)),
            ],
            options={
                'db_table': 'add_product',
            },
        ),
    ]
